[template] add requirements to "intro to jobs" template (#503)
When I run the “intro to jobs” template, everything works great until I
get to the “Submitting a Job programmatically” section. It fails with
ModuleNotFoundError: No module named 'emoji' (because it’s being run
outside the workspace). To fix this, we can add --requirements to the
command.

Final command
```
anyscale job submit \
  --name=zach-job-from-cli-with-reqs \
  --project=poc-project \
  --working-dir=. \
  --requirements=requirements.txt \
  --wait \
  -- python main.py
```

Before adding requirements:
https://console.anyscale.com/cld_4y8pizltk6d2k98rmfi1uteyy7/prj_sp1qpur34ghx7us7fvszw5vnb7/jobs/prodjob_949pthslhpewv8pbzuwdz1czrb?job-logs-section-tabs=application_logs&job-tab=overview

<img width="414" height="189" alt="Screenshot 2025-10-24 at 12 48 58 PM"
src="https://github.com/user-attachments/assets/d5f01dd0-d773-4f84-b8e1-61eca43009c3"
/>

After adding requirements:
https://console.anyscale.com/cld_4y8pizltk6d2k98rmfi1uteyy7/prj_sp1qpur34ghx7us7fvszw5vnb7/jobs/prodjob_3zf79eks1s2lceing57wc6hnk5?job-tab=overview&job-logs-section-tabs=application_logs

<img width="583" height="248" alt="Screenshot 2025-10-24 at 12 49 13 PM"
src="https://github.com/user-attachments/assets/0eadf7dd-f224-45e3-bd57-23d1e19f76a0"
/>